### ISSUE TITLE
How to modify the extension ae_loss code to fit Pytorch 1.0?

### ISSUE THREAD

**Issue by DouYishun** [princeton-vl/pose-ae-train#35]

**Comment by teamo429** [comment]
@DouYishun  I also encountered the same problem...
Do you solve it?

**Comment by DouYishun** [comment]
@teamo429 https://github.com/DouYishun/loss_collection/blob/master/AEloss/AE_loss.py

**Comment by FightStone** [comment]
@DouYishun Thank you for providing a python AELOSS. Have you tested it? What's the effect? Looking forward to your reply！
