### ISSUE TITLE
Refine predictions

### ISSUE THREAD

**Issue by USTClj** [princeton-vl/pose-ae-train#8]
In the paper, there goes **'we apply a single-person pose model [40] trained on the same dataset to further refine predictions.'**
Does this means during test, the code firstly estimate the initial joint locations and then crop the approximate person area, afterwords, estimate the cropped person using a single-person pose model?
It would be so nice if you could rely.

**Comment by zhengzhugithub** [comment]
> 
> 
> In the paper, there goes **'we apply a single-person pose model [40] trained on the same dataset to further refine predictions.'**
> Does this means during test, the code firstly estimate the initial joint locations and then crop the approximate person area, afterwords, estimate the cropped person using a single-person pose model?
> It would be so nice if you could rely.

Do you solve this question?
